// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only needed by `prisma migrate dev` (creates/drops a scratch DB to
    // detect drift) — `migrate deploy`, used in CI/Render, doesn't touch this.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
