"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import useSWR from "swr";
import { FileEdit, Plus, Receipt } from "lucide-react";
import type { countBillsByType, listBills } from "@/lib/services/bills";
import { swrFetcher } from "@/lib/api-client";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { EmptyState } from "@/components/empty-state";
import { BillsList } from "./bills-list";
import Loading from "../loading";

const FILTERS = [
  { id: "all", shortLabel: "All", label: "All" },
  { id: "app", shortLabel: "By App", label: "Generated by App" },
  { id: "self", shortLabel: "Self Made", label: "Self Generated" },
] as const;

type BillsData = {
  bills: Awaited<ReturnType<typeof listBills>>;
  counts: Awaited<ReturnType<typeof countBillsByType>>;
};

export default function BillsPage() {
  const searchParams = useSearchParams();
  const customerId = searchParams.get("customerId") ?? undefined;
  const filterParam = searchParams.get("filter");
  const activeFilter = FILTERS.find((f) => f.id === filterParam) ?? FILTERS[0];

  const query = new URLSearchParams();
  if (customerId) query.set("customerId", customerId);
  if (activeFilter.id !== "all") query.set("filter", activeFilter.id);
  const apiPath = `/api/bills${query.toString() ? `?${query.toString()}` : ""}`;

  const { data } = useSWR<BillsData>(apiPath, swrFetcher, { dedupingInterval: 15_000 });

  const filterHref = (filterId: string) => {
    const params = new URLSearchParams();
    if (customerId) params.set("customerId", customerId);
    if (filterId !== "all") params.set("filter", filterId);
    const qs = params.toString();
    return `/bills${qs ? `?${qs}` : ""}`;
  };

  if (!data) return <Loading />;
  const { bills, counts } = data;

  return (
    <div>
      <PageHeader
        title="Saved Bills"
        backHref={customerId ? `/customers/${customerId}` : undefined}
        action={
          <div className="flex shrink-0 gap-2">
            <Button
              size="lg"
              variant="secondary"
              className="h-11 px-2.5 sm:px-3"
              nativeButton={false}
              render={<Link href={customerId ? `/bills/new/direct?customerId=${customerId}` : "/bills/new/direct"} />}
            >
              <FileEdit className="size-5" />
              <span className="hidden sm:inline">Direct Bill</span>
              <span className="sm:hidden">Direct</span>
            </Button>
            <Button
              size="lg"
              className="h-11 px-2.5 sm:px-3"
              nativeButton={false}
              render={<Link href={customerId ? `/bills/new?customerId=${customerId}` : "/bills/new"} />}
            >
              <Plus className="size-5" />
              <span className="hidden sm:inline">Generate Bill</span>
              <span className="sm:hidden">Bill</span>
            </Button>
          </div>
        }
      />
      <div className="flex flex-col gap-3 px-4 pb-6 md:px-8">
        <div className="grid grid-cols-3 gap-2 rounded-lg bg-muted p-1 text-sm">
          {FILTERS.map((f) => {
            const count = f.id === "all" ? counts.all : f.id === "app" ? counts.app : counts.self;
            const isActive = activeFilter.id === f.id;
            return (
              <Link
                key={f.id}
                href={filterHref(f.id)}
                className={cn(
                  "flex flex-col items-center justify-center gap-0.5 rounded-md py-2 text-center font-semibold transition-colors",
                  isActive ? "bg-card text-foreground shadow-sm" : "text-muted-foreground",
                )}
              >
                <span className="hidden sm:inline">{f.label}</span>
                <span className="sm:hidden">{f.shortLabel}</span>
                <span className="text-xs font-normal text-muted-foreground">{count}</span>
              </Link>
            );
          })}
        </div>

        {bills.length === 0 ? (
          <EmptyState
            icon={Receipt}
            title="No Bills Yet"
            description="Generate your first bill once you've completed some work."
            actionLabel="Generate Bill"
            actionHref={customerId ? `/bills/new?customerId=${customerId}` : "/bills/new"}
          />
        ) : (
          <BillsList bills={bills} />
        )}
      </div>
    </div>
  );
}
