"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import useSWR from "swr";
import { FileEdit, Loader2, Plus, Receipt, Table2 } from "lucide-react";
import type { countBillsByType, listBills } from "@/lib/services/bills";
import { apiFetch, swrFetcher } from "@/lib/api-client";
import type { Plain } from "@/lib/plain";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { FormAlert } from "@/components/bill/editor/form-parts";
import { cn } from "@/lib/utils";
import { EmptyState } from "@/components/empty-state";
import { BillsList } from "./bills-list";
import { ExportRegisterButton } from "./export-register-button";
import Loading from "../loading";

const FILTERS = [
  { id: "all", shortLabel: "All", label: "All" },
  { id: "app", shortLabel: "By App", label: "Generated by App" },
  { id: "self", shortLabel: "Self Made", label: "Self Generated" },
] as const;

type BillRow = Plain<Awaited<ReturnType<typeof listBills>>["items"][number]>;
type BillsData = {
  bills: BillRow[];
  counts: Awaited<ReturnType<typeof countBillsByType>>;
  nextCursor: string | null;
};

/** Bills are loaded this many at a time; "Load more" fetches the next page. */
const PAGE_SIZE = 50;

export default function BillsPage() {
  const searchParams = useSearchParams();
  const customerId = searchParams.get("customerId") ?? undefined;
  const filterParam = searchParams.get("filter");
  const activeFilter = FILTERS.find((f) => f.id === filterParam) ?? FILTERS[0];

  // Search text: typed immediately, sent to the server a moment after the user
  // stops typing. Filtering and search happen on the SERVER so they cover every
  // bill, not just the pages already loaded (pagination made client-side
  // filtering incomplete).
  const [queryInput, setQueryInput] = useState("");
  const [query, setQuery] = useState("");
  useEffect(() => {
    const timer = setTimeout(() => setQuery(queryInput.trim()), 300);
    return () => clearTimeout(timer);
  }, [queryInput]);

  const apiPath =
    `/api/bills?limit=${PAGE_SIZE}` +
    (customerId ? `&customerId=${encodeURIComponent(customerId)}` : "") +
    (activeFilter.id !== "all" ? `&filter=${activeFilter.id}` : "") +
    (query ? `&q=${encodeURIComponent(query)}` : "");
  // keepPreviousData: while a new filter/search loads, keep showing the current
  // list (and keep the search box mounted and focused) instead of a full-page spinner.
  const { data, isValidating } = useSWR<BillsData>(apiPath, swrFetcher, {
    dedupingInterval: 15_000,
    keepPreviousData: true,
  });

  // Pages after the first are held locally. They are tied to the exact first-
  // page response they continue (`forData`), so a revalidation (a payment, an
  // edit, a delete) or a different customer silently drops them instead of
  // showing stale rows.
  const [more, setMore] = useState<{ forData: BillsData; bills: BillRow[]; nextCursor: string | null } | null>(null);
  const [loadingMore, setLoadingMore] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);

  const extra = data && more && more.forData === data ? more : null;
  const nextCursor = data ? (extra ? extra.nextCursor : data.nextCursor) : null;

  const bills = data ? (extra ? [...data.bills, ...extra.bills] : data.bills) : undefined;

  async function loadMore() {
    if (!nextCursor || !data) return;
    setLoadingMore(true);
    setLoadError(null);
    try {
      const page = await apiFetch<BillsData>(`${apiPath}&cursor=${encodeURIComponent(nextCursor)}`);
      setMore({ forData: data, bills: [...(extra?.bills ?? []), ...page.bills], nextCursor: page.nextCursor });
    } catch (err) {
      setLoadError(err instanceof Error ? err.message : "Could not load more bills");
    } finally {
      setLoadingMore(false);
    }
  }

  const filterHref = (filterId: string) => {
    const params = new URLSearchParams();
    if (customerId) params.set("customerId", customerId);
    if (filterId !== "all") params.set("filter", filterId);
    const qs = params.toString();
    return `/bills${qs ? `?${qs}` : ""}`;
  };

  if (!data || !bills) return <Loading />;
  const { counts } = data;

  const exportQuery = (() => {
    const params = new URLSearchParams();
    if (customerId) params.set("customerId", customerId);
    if (activeFilter.id !== "all") params.set("filter", activeFilter.id);
    if (query) params.set("q", query);
    const qs = params.toString();
    return qs ? `?${qs}` : "";
  })();

  return (
    <div>
      <PageHeader
        title="Saved Bills"
        backHref={customerId ? `/customers/detail?id=${customerId}` : undefined}
        action={
          <div className="flex flex-wrap gap-1.5 sm:gap-2">
            <Button
              size="lg"
              variant="secondary"
              className="h-11 px-2 text-amber-800 sm:px-3 dark:text-secondary-foreground"
              nativeButton={false}
              render={<Link href="/bills/new/summary" />}
            >
              <Table2 aria-hidden className="size-5" />
              <span className="hidden sm:inline">Summary Bill</span>
              <span className="sm:hidden">Summary</span>
            </Button>
            <Button
              size="lg"
              variant="secondary"
              className="h-11 px-2 text-amber-800 sm:px-3 dark:text-secondary-foreground"
              nativeButton={false}
              render={<Link href={customerId ? `/bills/new/direct?customerId=${customerId}` : "/bills/new/direct"} />}
            >
              <FileEdit aria-hidden className="size-5" />
              <span className="hidden sm:inline">Direct Bill</span>
              <span className="sm:hidden">Direct</span>
            </Button>
            <Button
              size="lg"
              className="h-11 px-2 sm:px-3"
              nativeButton={false}
              render={<Link href={customerId ? `/bills/new?customerId=${customerId}` : "/bills/new"} />}
            >
              <Plus aria-hidden className="size-5" />
              <span className="hidden sm:inline">Generate Bill</span>
              <span className="sm:hidden">Bill</span>
            </Button>
          </div>
        }
      />
      <div className="flex flex-col gap-3 px-4 pb-6 md:px-8">
        <div className="grid grid-cols-3 gap-2 rounded-lg bg-muted p-1 text-sm">
          {FILTERS.map((f) => {
            const count = f.id === "all" ? counts.all : f.id === "app" ? counts.app : counts.self;
            const isActive = activeFilter.id === f.id;
            return (
              <Link
                key={f.id}
                href={filterHref(f.id)}
                aria-current={isActive ? "page" : undefined}
                className={cn(
                  "flex min-h-11 flex-col items-center justify-center gap-0.5 rounded-md py-2 text-center font-semibold transition-colors outline-none focus-visible:ring-3 focus-visible:ring-ring/50",
                  isActive ? "bg-card text-foreground shadow-sm" : "text-foreground/70",
                )}
              >
                <span className="hidden sm:inline">{f.label}</span>
                <span className="sm:hidden">{f.shortLabel}</span>
                <span className="text-xs font-normal">{count}</span>
              </Link>
            );
          })}
        </div>

        {bills.length === 0 && !nextCursor && !query && activeFilter.id === "all" ? (
          <EmptyState
            icon={Receipt}
            title="No Bills Yet"
            description="Generate your first bill once you've completed some work."
            actionLabel="Generate Bill"
            actionHref={customerId ? `/bills/new?customerId=${customerId}` : "/bills/new"}
          />
        ) : (
          <>
            <div className="self-start">
              <ExportRegisterButton query={exportQuery} />
            </div>
            <BillsList bills={bills} query={queryInput} onQueryChange={setQueryInput} searching={isValidating || queryInput.trim() !== query} />
            {nextCursor && (
              <Button type="button" variant="secondary" size="lg" className="h-11 text-amber-800 dark:text-secondary-foreground" disabled={loadingMore} onClick={loadMore}>
                {loadingMore ? <Loader2 aria-label="Loading" className="size-4 animate-spin" /> : "Load more"}
              </Button>
            )}
            {loadError && <FormAlert>{loadError}</FormAlert>}
          </>
        )}
      </div>
    </div>
  );
}
