#!/usr/bin/env node
/**
 * Control scoreboard: facts about the controls, computed from the repository, replacing
 * lines-of-code / route-count style numbers that say nothing about quality.
 *
 *   npm run scoreboard             # print to the terminal
 *   npm run scoreboard -- --write  # also write docs/scoreboard.md
 *
 * Everything here is a STATIC COUNT of files in this checkout (nothing is run, no database is touched,
 * no CI result is read). Counts of tests are lexical (an `it.each` counts once however many rows it
 * expands to). Anything that needs production, the hosting providers or a human is listed at the bottom
 * as UNVERIFIED instead of being guessed.
 */
import fs from "node:fs";
import path from "node:path";
import { buildInventory } from "./lib/route-inventory.mjs";
import { CHECKS, CONTROL_CHECKS } from "./lib/integrity-checks.mjs";

const walk = (dir, accept) =>
  fs.existsSync(dir)
    ? fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
        const p = path.join(dir, e.name);
        return e.isDirectory() ? walk(p, accept) : accept(p) ? [p] : [];
      })
    : [];
const read = (f) => fs.readFileSync(f, "utf8");
const count = (text, re) => (text.match(re) ?? []).length;

const rows = buildInventory(".");
const mutating = rows.filter((r) => r.mutating && r.principal !== "NONE");
const testFiles = walk("tests", (p) => p.endsWith(".test.ts"));
const dbBacked = testFiles.filter((f) => /createTenant|@\/lib\/db/.test(read(f)));
const testCases = testFiles.reduce((n, f) => n + count(read(f), /^\s*(?:it|test)(?:\.each\([^)]*\))?\(/gm), 0);

const matrixSrc = fs.existsSync("tests/security/cross-tenant-matrix.test.ts") ? read("tests/security/cross-tenant-matrix.test.ts") : "";
const matrixCases = count(matrixSrc, /^\s*c\("/gm);
const matrixFeeds = count(matrixSrc, /^\s*\["GET /gm);

const serviceFiles = walk("src", (p) => p.endsWith(".ts") || p.endsWith(".tsx")).filter((f) => !f.includes("generated"));
const auditSites = serviceFiles.reduce((n, f) => n + count(read(f), /\brecordAudit\(/g), 0);
const auditActions = new Set();
for (const f of serviceFiles) for (const m of read(f).matchAll(/action:\s*(?:[a-z]+\s*\?\s*)?"([A-Za-z.]+)"/g)) auditActions.add(m[1]);

const ci = fs.existsSync(".github/workflows/ci.yml") ? read(".github/workflows/ci.yml") : "";
const ciSteps = count(ci, /^\s+- name:/gm);
const workflows = fs.existsSync(".github/workflows") ? fs.readdirSync(".github/workflows").filter((f) => f.endsWith(".yml")) : [];
const migrations = fs.existsSync("prisma/migrations") ? fs.readdirSync("prisma/migrations").filter((d) => /^\d/.test(d)) : [];
const models = count(read("prisma/schema.prisma"), /^model /gm);

const docs = fs.existsSync("docs") ? fs.readdirSync("docs").filter((f) => f.endsWith(".md")).length : 0;
const adrs = fs.existsSync("docs/adr") ? fs.readdirSync("docs/adr").filter((f) => f.endsWith(".md")).length : 0;

const pct = (a, b) => (b === 0 ? "n/a" : `${a}/${b} (${Math.round((100 * a) / b)}%)`);

const lines = [
  "# Control scoreboard",
  "",
  "Generated by `npm run scoreboard -- --write` from this checkout. **Static counts only**: nothing was run, no",
  "database was read, and no CI result was consulted. A number here says a control is *present*, not that it is",
  "*working today* — see [assurance.md](assurance.md) for evidence quality. Re-generate after changing controls.",
  "",
  "## Controls present in the repository",
  "",
  "| Control | Measure | Value |",
  "|---|---|---|",
  `| Authentication guard on every API route | route/method pairs guarded vs total (the rest are the justified public list) | ${pct(rows.filter((r) => r.principal !== "NONE").length, rows.length)} |`,
  `| Idempotent creates | mutating authenticated routes using an Idempotency-Key | ${pct(mutating.filter((r) => r.idempotent).length, mutating.length)} |`,
  `| Optimistic concurrency | mutating authenticated routes accepting \`expectedVersion\` | ${pct(mutating.filter((r) => r.versioned).length, mutating.length)} |`,
  `| Cross-tenant negative tests | id-addressed handler cases in the isolation matrix | ${matrixCases} |`,
  `| Cross-tenant feed checks | list/search/dashboard feeds asserted to leak nothing | ${matrixFeeds} |`,
  `| Audit trail coverage | \`recordAudit\` call sites / distinct audit actions | ${auditSites} / ${auditActions.size} |`,
  `| Data integrity rules | SQL checks run by \`npm run audit:integrity\` (data rules + database controls; plus the generic orphan scan) | ${CHECKS.length + CONTROL_CHECKS.length} + 1 |`,
  `| Test files / of which DB-backed | static count | ${testFiles.length} / ${dbBacked.length} |`,
  `| Test cases | lexical count of it()/test() | ${testCases} |`,
  `| CI | workflows / steps in the main CI workflow | ${workflows.length} / ${ciSteps} |`,
  `| Schema | models / migrations | ${models} / ${migrations.length} |`,
  `| Documentation | markdown docs / decision records | ${docs} / ${adrs} |`,
  "",
  "Reading the percentages: idempotency keys are applied deliberately to the routes that CREATE money records",
  "(bills, payments) and `expectedVersion` to records that can be edited concurrently; neither is meant to cover",
  "every mutation, so a low percentage is not a target to raise. The authentication row is different: the only",
  "unguarded routes are the justified public list in `scripts/lib/route-inventory.mjs`.",
  "",
  "## Not measured here (UNVERIFIED or NOT DONE)",
  "",
  "| Metric | Why it is not in this table |",
  "|---|---|",
  "| Critical workflows with a passing test today | needs a CI run; the list of workflows and their tests is in assurance.md §2.3 |",
  "| Production p95 latency of bill creation, error rate, uptime | no production monitoring exists (assurance.md D13) |",
  "| Provider backup restore time (real RTO) | never performed; only the logical drill (docs/runbook-recovery.md §6) is recorded |",
  "| Date each secret was last rotated | no rotation log exists |",
  "| Known critical vulnerabilities | run `npm audit --omit=dev` at release time (CI gates on critical) |",
  "| SLO attainment, error budget, DORA metrics | no SLO is defined; deployment history lives in GitHub/Render |",
  "| Line coverage | deliberately not used (assurance.md §2.3) |",
  "",
];

const out = lines.join("\n");
console.log(out);
if (process.argv.includes("--write")) {
  fs.writeFileSync("docs/scoreboard.md", out);
  console.error("\nwrote docs/scoreboard.md");
}
